DocWorks for wix-stores-backend - 15 changes detected, but 9 issue detected changes: Service wix-stores-backend operation updateInventoryVariantByExternalId has changed param inventoryExternalId doc Service wix-stores-backend operation updateInventoryVariantByExternalId.examples has 2 examples removed Service wix-stores-backend operation updateInventoryVariantById.examples has 2 examples removed Service wix-stores-backend operation updateVariantData.examples[0] has changed body Service wix-stores-backend message InventoryItem member id was removed Service wix-stores-backend message InventoryItem member externalId has changed doc Service wix-stores-backend message InventoryItem member trackQuantity has changed doc Service wix-stores-backend message InventoryItem has a new member _id Service wix-stores-backend message InventoryItem.examples[0] has changed title Service wix-stores-backend message InventoryItem.examples[0] has changed body Service wix-stores-backend message InventoryItem.examples has 2 examples removed Service wix-stores-backend message InventoryItemVariantInfo member externalId has changed doc Service wix-stores-backend message InventoryItemVariantInfo.examples has 2 examples removed Service wix-stores-backend message InventoryItemVariantItems member inStock has changed doc Service wix-stores-backend message InventoryItemVariantItems member quantity has changed doc
issues:
Message ProductCreatedEvent has an unknown property type $w.Gallery.VideoItem (events.js (216))
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-InventoryVariantUpdateById.es6' not found. File: inventory.js line: 1
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-InventoryVariantUpdateByExternalId.es6' not found. File: inventory.js line: 1
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-InventoryVariantUpdateById.es6' not found. File: inventory.js line: 21
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-InventoryVariantUpdateByExternalId.es6' not found. File: inventory.js line: 21
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-InventoryVariantUpdateById.es6' not found. File: inventory.js line: 59
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-InventoryVariantUpdateByExternalId.es6' not found. File: inventory.js line: 59
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-InventoryVariantUpdateById.es6' not found. File: inventory.js line: 80
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-InventoryVariantUpdateByExternalId.es6' not found. File: inventory.js line: 80