DocWorks for wixstore-client-worker - 150 changes detected, but 8 issue detected changes: Service $w.CartIcon has changed summary Service $w.CartIcon has changed description Service $w.CartIcon operation addProductsToCart was removed Service $w.CartIcon operation addToCart has changed param productID doc Service $w.CartIcon operation addToCart has changed param quantity doc Service $w.CartIcon operation addToCart has changed param options doc Service $w.CartIcon operation addToCart has changed return doc Service $w.CartIcon operation addToCart has changed summary Service $w.CartIcon operation addToCart has changed description Service $w.CartIcon operation addToCart.examples[0] has changed title Service $w.CartIcon operation addToCart.examples[1] has changed title Service $w.CartIcon operation addToCart.examples[2] has changed title Service $w.CartIcon operation addToCart.examples[3] has changed title Service $w.CartIcon message AddToCartCustomTextField member title has changed doc Service $w.CartIcon message AddToCartCustomTextField member value has changed doc Service $w.CartIcon message AddToCartCustomTextField has changed summary Service $w.CartIcon message AddToCartCustomTextField has a new link [addToCart( )](#addToCart) Service $w.CartIcon message AddToCartCustomTextField link [addToCart( )](#addToCart) was removed Service $w.CartIcon message AddToCartCustomTextField.examples has 2 examples removed Service $w.CartIcon message AddToCartItem was removed Service $w.CartIcon message AddToCartOptions member choices has changed doc Service $w.CartIcon message AddToCartOptions member customTextField has changed doc Service $w.CartIcon message AddToCartOptions has changed summary Service $w.CartIcon message AddToCartOptions has a new link [addToCart( )](#addToCart) Service $w.CartIcon message AddToCartOptions link [addToCart( )](#addToCart) was removed Service $w.CartIcon message AddToCartOptions.examples has 2 examples removed Service $w.ProductPage message Product member variants has changed type Service $w.ProductPage message ProductVariantItem was removed Service $w.ProductPage message ProductVariants was removed Service $w.ThankYouPage has changed summary Service $w.ThankYouPage operation getOrder has changed return doc Service $w.ThankYouPage operation getOrder has changed summary Service $w.ThankYouPage operation getOrder has changed description Service $w.ThankYouPage operation getOrder.examples[0] has changed title Service $w.ThankYouPage operation getOrder.examples[0] has changed body Service $w.ThankYouPage message Address member addressLine has changed doc Service $w.ThankYouPage message Address member subdivision has changed doc Service $w.ThankYouPage message Address member city has changed doc Service $w.ThankYouPage message Address member postalCode has changed doc Service $w.ThankYouPage message Address member country has changed doc Service $w.ThankYouPage message Address member formatted has changed doc Service $w.ThankYouPage message Address has changed summary Service $w.ThankYouPage message Address.examples[0] has changed title Service $w.ThankYouPage message Address.examples[0] has changed body Service $w.ThankYouPage message BillingInfo member firstName has changed doc Service $w.ThankYouPage message BillingInfo member lastName has changed doc Service $w.ThankYouPage message BillingInfo member email has changed doc Service $w.ThankYouPage message BillingInfo member phone has changed doc Service $w.ThankYouPage message BillingInfo member company has changed doc Service $w.ThankYouPage message BillingInfo member vatId has changed doc Service $w.ThankYouPage message BillingInfo member address has changed doc Service $w.ThankYouPage message BillingInfo has changed summary Service $w.ThankYouPage message BillingInfo.examples[0] has changed title Service $w.ThankYouPage message BillingInfo.examples[0] has changed body Service $w.ThankYouPage message BuyerInfo member id has changed doc Service $w.ThankYouPage message BuyerInfo member email has changed doc Service $w.ThankYouPage message BuyerInfo member firstName has changed doc Service $w.ThankYouPage message BuyerInfo member lastName has changed doc Service $w.ThankYouPage message BuyerInfo member identityType has changed doc Service $w.ThankYouPage message BuyerInfo member phone has changed doc Service $w.ThankYouPage message BuyerInfo has changed summary Service $w.ThankYouPage message BuyerInfo.examples[0] has changed title Service $w.ThankYouPage message BuyerInfo.examples[0] has changed body Service $w.ThankYouPage message CustomTextField member title has changed doc Service $w.ThankYouPage message CustomTextField member value has changed doc Service $w.ThankYouPage message CustomTextField has changed summary Service $w.ThankYouPage message CustomTextField.examples[0] has changed title Service $w.ThankYouPage message CustomTextField.examples[0] has changed body Service $w.ThankYouPage message LineItem member name has changed doc Service $w.ThankYouPage message LineItem member notes has changed doc Service $w.ThankYouPage message LineItem member price has changed doc Service $w.ThankYouPage message LineItem member productId has changed doc Service $w.ThankYouPage message LineItem member quantity has changed doc Service $w.ThankYouPage message LineItem member sku has changed doc Service $w.ThankYouPage message LineItem member totalPrice has changed doc Service $w.ThankYouPage message LineItem member weight has changed type Service $w.ThankYouPage message LineItem member weight has changed doc Service $w.ThankYouPage message LineItem member lineItemType has changed doc Service $w.ThankYouPage message LineItem member options has changed doc Service $w.ThankYouPage message LineItem member mediaItem has changed doc Service $w.ThankYouPage message LineItem member customTextFields has changed doc Service $w.ThankYouPage message LineItem member index has changed doc Service $w.ThankYouPage message LineItem has changed summary Service $w.ThankYouPage message LineItem.examples[0] has changed title Service $w.ThankYouPage message LineItem.examples[0] has changed body Service $w.ThankYouPage message MediaItem member mediaType has changed doc Service $w.ThankYouPage message MediaItem member url has changed doc Service $w.ThankYouPage message MediaItem member height has changed doc Service $w.ThankYouPage message MediaItem member width has changed doc Service $w.ThankYouPage message MediaItem has changed summary Service $w.ThankYouPage message MediaItem.examples[0] has changed title Service $w.ThankYouPage message MediaItem.examples[0] has changed body Service $w.ThankYouPage message Option member option has changed doc Service $w.ThankYouPage message Option member selection has changed doc Service $w.ThankYouPage message Option has changed summary Service $w.ThankYouPage message Option.examples[0] has changed title Service $w.ThankYouPage message Option.examples[0] has changed body Service $w.ThankYouPage message Order member _id has changed doc Service $w.ThankYouPage message Order member _dateCreated has changed doc Service $w.ThankYouPage message Order member number has changed doc Service $w.ThankYouPage message Order member currency has changed doc Service $w.ThankYouPage message Order member billingInfo has changed doc Service $w.ThankYouPage message Order member buyerInfo has changed doc Service $w.ThankYouPage message Order member lineItems has changed doc Service $w.ThankYouPage message Order member totals has changed doc Service $w.ThankYouPage message Order member weightUnit has changed doc Service $w.ThankYouPage message Order member shippingInfo has changed doc Service $w.ThankYouPage message Order member buyerNote has changed doc Service $w.ThankYouPage message Order has changed summary Service $w.ThankYouPage message Order has a new link [getOrder( )](#getOrder) Service $w.ThankYouPage message Order link [getOrder( )](#getOrder) was removed Service $w.ThankYouPage message Order.examples[0] has changed title Service $w.ThankYouPage message Order.examples[0] has changed body Service $w.ThankYouPage message PickupDetails member pickupInstructions has changed doc Service $w.ThankYouPage message PickupDetails member pickupAddress has changed doc Service $w.ThankYouPage message PickupDetails member firstName has changed doc Service $w.ThankYouPage message PickupDetails member lastName has changed doc Service $w.ThankYouPage message PickupDetails member email has changed doc Service $w.ThankYouPage message PickupDetails member phone has changed doc Service $w.ThankYouPage message PickupDetails has changed summary Service $w.ThankYouPage message PickupDetails.examples[0] has changed title Service $w.ThankYouPage message PickupDetails.examples[0] has changed body Service $w.ThankYouPage message ShipmentDetails member address has changed doc Service $w.ThankYouPage message ShipmentDetails member firstName has changed doc Service $w.ThankYouPage message ShipmentDetails member lastName has changed doc Service $w.ThankYouPage message ShipmentDetails member email has changed doc Service $w.ThankYouPage message ShipmentDetails member phone has changed doc Service $w.ThankYouPage message ShipmentDetails has changed summary Service $w.ThankYouPage message ShipmentDetails.examples[0] has changed title Service $w.ThankYouPage message ShipmentDetails.examples[0] has changed body Service $w.ThankYouPage message ShippingInfo member deliveryOption has changed doc Service $w.ThankYouPage message ShippingInfo member estimatedDeliveryTime has changed doc Service $w.ThankYouPage message ShippingInfo has changed summary Service $w.ThankYouPage message ShippingInfo.examples[0] has changed title Service $w.ThankYouPage message ShippingInfo.examples[0] has changed body Service $w.ThankYouPage message Totals member subtotal has changed doc Service $w.ThankYouPage message Totals member shipping has changed doc Service $w.ThankYouPage message Totals member tax has changed doc Service $w.ThankYouPage message Totals member discount has changed doc Service $w.ThankYouPage message Totals member total has changed doc Service $w.ThankYouPage message Totals member weight has changed doc Service $w.ThankYouPage message Totals member quantity has changed doc Service $w.ThankYouPage message Totals has changed summary Service $w.ThankYouPage message Totals.examples[0] has changed title Service $w.ThankYouPage message Totals.examples[0] has changed body Service $w.ThankYouPage message VatId member number has changed doc Service $w.ThankYouPage message VatId member type has changed doc Service $w.ThankYouPage message VatId has changed summary Service $w.ThankYouPage message VatId.examples[0] has changed title Service $w.ThankYouPage message VatId.examples[0] has changed body
issues:
Message Product has an unknown property type $w.ProductPage.Variants (wixCodeDoc.js (195))
Mixin $w.Element not found (wixCodeDoc.js (1))
Mixin $w.HiddenCollapsedMixin not found (wixCodeDoc.js (1))
Mixin $w.Element not found (wixCodeDoc.js (254))
Mixin $w.HiddenCollapsedMixin not found (wixCodeDoc.js (254))
Mixin $w.Element not found (wixCodeDoc.js (329))
Mixin $w.HiddenCollapsedMixin not found (wixCodeDoc.js (329))
ERROR: The @snippet tag - file 'examples/Stores-backend-getProductVariants_ids.es6' not found. File: wixCodeDoc.js line: 126