DocWorks for js-wixcode-sdk - 74 changes detected, but 12 issue detected changes: Service $w.Background message BackgroundOptions member src has changed doc Service $w.Background message BackgroundOptions has changed description Service $w.Document message BackgroundOptions member src has changed doc Service $w.Document message BackgroundOptions has changed description Service $w.EffectOptions message ArcEffectOptions member duration has changed doc Service $w.EffectOptions message ArcEffectOptions member delay has changed doc Service $w.EffectOptions message ArcEffectOptions member direction has changed doc Service $w.EffectOptions message ArcEffectOptions has changed description Service $w.EffectOptions message BounceEffectOptions member duration has changed doc Service $w.EffectOptions message BounceEffectOptions member delay has changed doc Service $w.EffectOptions message BounceEffectOptions member direction has changed doc Service $w.EffectOptions message BounceEffectOptions member intensity has changed doc Service $w.EffectOptions message BounceEffectOptions has changed description Service $w.EffectOptions message FadeEffectOptions member duration has changed doc Service $w.EffectOptions message FadeEffectOptions member delay has changed doc Service $w.EffectOptions message FadeEffectOptions has changed description Service $w.EffectOptions message FlipEffectOptions member duration has changed doc Service $w.EffectOptions message FlipEffectOptions member delay has changed doc Service $w.EffectOptions message FlipEffectOptions member direction has changed doc Service $w.EffectOptions message FlipEffectOptions has changed description Service $w.EffectOptions message FloatEffectOptions member duration has changed doc Service $w.EffectOptions message FloatEffectOptions member delay has changed doc Service $w.EffectOptions message FloatEffectOptions member direction has changed doc Service $w.EffectOptions message FloatEffectOptions has changed description Service $w.EffectOptions message FlyEffectOptions member duration has changed doc Service $w.EffectOptions message FlyEffectOptions member delay has changed doc Service $w.EffectOptions message FlyEffectOptions member direction has changed doc Service $w.EffectOptions message FlyEffectOptions has changed description Service $w.EffectOptions message FoldEffectOptions member duration has changed doc Service $w.EffectOptions message FoldEffectOptions member delay has changed doc Service $w.EffectOptions message FoldEffectOptions member direction has changed doc Service $w.EffectOptions message FoldEffectOptions has changed description Service $w.EffectOptions message GlideEffectOptions member duration has changed doc Service $w.EffectOptions message GlideEffectOptions member delay has changed doc Service $w.EffectOptions message GlideEffectOptions member angle has changed doc Service $w.EffectOptions message GlideEffectOptions member distance has changed doc Service $w.EffectOptions message GlideEffectOptions has changed description Service $w.EffectOptions message PuffEffectOptions member duration has changed doc Service $w.EffectOptions message PuffEffectOptions member delay has changed doc Service $w.EffectOptions message PuffEffectOptions has changed description Service $w.EffectOptions message RollEffectOptions member duration has changed doc Service $w.EffectOptions message RollEffectOptions member delay has changed doc Service $w.EffectOptions message RollEffectOptions member direction has changed doc Service $w.EffectOptions message RollEffectOptions has changed description Service $w.EffectOptions message SlideEffectOptions member duration has changed doc Service $w.EffectOptions message SlideEffectOptions member delay has changed doc Service $w.EffectOptions message SlideEffectOptions member direction has changed doc Service $w.EffectOptions message SlideEffectOptions has changed description Service $w.EffectOptions message SpinEffectOptions member duration has changed doc Service $w.EffectOptions message SpinEffectOptions member delay has changed doc Service $w.EffectOptions message SpinEffectOptions member direction has changed doc Service $w.EffectOptions message SpinEffectOptions member cycles has changed doc Service $w.EffectOptions message SpinEffectOptions has changed description Service $w.EffectOptions message TurnEffectOptions member duration has changed doc Service $w.EffectOptions message TurnEffectOptions member delay has changed doc Service $w.EffectOptions message TurnEffectOptions member direction has changed doc Service $w.EffectOptions message TurnEffectOptions has changed description Service $w.EffectOptions message ZoomEffectOptions member duration has changed doc Service $w.EffectOptions message ZoomEffectOptions member delay has changed doc Service $w.EffectOptions message ZoomEffectOptions has changed description Service $w.HiddenMixin operation show has changed description Service $w.QuickActionBarItemClickedEvent message QuickActionBarItem member itemType has changed doc Service $w.QuickActionBarItemClickedEvent message QuickActionBarItem has changed description Service $w.ValidatableMixin message ValidityState has changed description Service site-monitoring.LogEntry message LogEntryOperation has changed description Service site-monitoring.LogEntry message LogEntryOperation has changed extra.notes Service wix-site operation getSiteStructure has changed description Service wix-site message Prefix member type has changed doc Service wix-site message Prefix has changed description Service wix-site message SiteStructure member pages has changed doc Service wix-site message SiteStructure has changed description Service wix-site message StructurePage has changed description Service wix-window.trackingParameters message CustomEvent has changed description Service wix-window operation trackEvent has changed description
issues:
Property zoom is missing a type annotation (GoogleMap.es6 (235))
Property center is defined two or more times (GoogleMap.es6 (159, 194))
Property zoom is defined two or more times (GoogleMap.es6 (211, 235))
Property markers has mismatching types for get ($w.GoogleMap.markers) and set ($w.GoogleMap) (GoogleMap.es6 (107, 142))
Operation postMessage has an unknown param type * (HtmlComponent.es6 (143))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (101))
Callback GoogleMapClickEvent is defined two or more times (GoogleMapClickEvent.es6 (4, 10))
Property value has an unknown type * (ValueMixin.es6 (56))
Property value has an unknown type * (ValueMixin.es6 (84))
ERROR: The @description tag requires a value. File: document.es6, line: 106
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 383
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 391