DocWorks for js-wixcode-sdk - 42 changes detected, but 11 issue detected changes: Service $w.Anchor has changed summary Service $w.Anchor has changed description Service $w.Box has changed summary Service $w.Box has changed description Service $w.CheckboxGroup has changed summary Service $w.CheckboxGroup has changed description Service $w.CollapsedMixin has changed summary Service $w.CollapsedMixin has changed description Service $w.ContainableMixin has changed summary Service $w.ContainableMixin has changed description Service $w.DatePicker property minDate has changed description Service $w.Dropdown has changed summary Service $w.Dropdown has changed description Service $w.Event property context has changed summary Service $w.FocusMixin has changed summary Service $w.FocusMixin has changed description Service $w.HiddenMixin has changed summary Service $w.HiddenMixin has changed description Service $w.HoverBox has changed summary Service $w.HoverBox has changed description Service $w.HtmlComponent has changed summary Service $w.HtmlComponent has changed description Service $w.Image has changed summary Service $w.Image has changed description Service $w.MenuContainer has changed summary Service $w.MenuContainer has changed description Service $w.MouseEvent has changed description Service $w.QuickActionBar has changed summary Service $w.QuickActionBar has changed description Service $w.RadioButtonGroup has changed summary Service $w.RadioButtonGroup has changed description Service $w.Repeater has changed description Service $w.Repeater property data has changed description Service $w.Slideshow property slides.examples[0] has changed title Service $w.Style has changed summary Service $w.Style has changed description Service $w.Text has changed description Service $w.UploadButton has changed description Service $w.ValidatableMixin has changed summary Service $w.ValidatableMixin has changed description Service $w has changed summary Service $w has changed description
issues:
Property zoom is missing a type annotation (GoogleMap.es6 (235))
Property center is defined two or more times (GoogleMap.es6 (159, 194))
Property zoom is defined two or more times (GoogleMap.es6 (211, 235))
Property markers has mismatching types for get ($w.GoogleMap.markers) and set ($w.GoogleMap) (GoogleMap.es6 (107, 142))
Operation postMessage has an unknown param type * (HtmlComponent.es6 (143))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (102))
Callback GoogleMapClickEvent is defined two or more times (GoogleMapClickEvent.es6 (4, 10))
Property value has an unknown type * (ValueMixin.es6 (56))
Property value has an unknown type * (ValueMixin.es6 (84))
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 381
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 389